flask_app:
  ros__parameters:
    appAddress: "192.168.0.3"
    portApp: 5050

camera:
  ros__parameters:
    address: "192.168.0.3"
    port: 8090
    input_topic: "/camera/color/image_raw/compressed"

rosbridge_websocket:
  ros__parameters:
    address: "192.168.0.3"
    port: 9090

